modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="littlejoys"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="littlejoys.png"
credits="${credits}"
authors="${mod_author}"
description='''${description}'''
[[mixins]]
config = "littlejoys.mixins.json"
[[mixins]]
config = "littlejoys.forge.mixins.json"
[[dependencies.littlejoys]]
modId="forge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.littlejoys]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
[[dependencies.littlejoys]]
modId="balm"
mandatory=true
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.littlejoys]]
modId="shogi"
mandatory=true
versionRange="[${shogi_version},)"
ordering="NONE"
side="BOTH"
