modLoader="javafml"
loaderVersion="[1,)"
license="${license}"
issueTrackerURL="${issues}"
[[mods]]
modId="littlejoys"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="littlejoys.png"
credits="${credits}"
authors="${mod_author}"
description='''${description}'''
[[mixins]]
config = "littlejoys.mixins.json"
[[mixins]]
config = "littlejoys.neoforge.mixins.json"
[[dependencies.littlejoys]]
modId="neoforge"
type="required"
versionRange="[${neoforge_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.littlejoys]]
modId="minecraft"
type="required"
versionRange="[${minecraft_version},)"
ordering="NONE"
side="BOTH"
[[dependencies.littlejoys]]
modId="balm"
type="required"
versionRange="[${balm_version},)"
ordering="NONE"
side="BOTH"
