dependencies {
    implementation(libs.balmNeoForge) {
        changing = libs.versions.balm.get().endsWith("SNAPSHOT")
    }
    compileOnly("curse.maven:aquaculture-60028:6393086")
    //compileOnly("curse.maven:cloth-config-348521:5729127")
    compileOnly("curse.maven:tide-884685:6312322")
    compileOnly("curse.maven:fishing-overhaul-491332:6297557")
}